# Generated by Django 5.1.3 on 2024-11-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0006_booking_reservation_date_booking_reservation_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_slot',
            field=models.CharField(max_length=20),
        ),
    ]
