# Generated by Django 5.1.3 on 2024-11-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0007_alter_booking_reservation_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
